Repository OriginTrail/dkg.js, pull requests merged in 2023-08, with the labels that each got.

#95 Open blockchain api into PR for handling already known issue
  index.js
  managers/blockchain-operations-manager.js
  services/blockchain-service/blockchain-service-base.js
  services/blockchain-service/implementations/node-blockchain-service.js
  services/input-service.js
Labels: enhancement

#93 Improvements for handling already known issue
  constants.js
  dist/dkg.min.js
  index.js
  managers/blockchain-operations-manager.js
  package-lock.json
  package.json
  services/blockchain-service/blockchain-service-base.js
  services/blockchain-service/implementations/browser-blockchain-service.js
  services/blockchain-service/implementations/node-blockchain-service.js
  services/input-service.js
  services/validation-service.js
Labels: bug

#88 fix browser support
  dist/dkg.min.js
  dist/dkg.min.js.LICENSE.txt
  examples/demo.html
  package-lock.json
  package.json
  services/blockchain-service/blockchain-service-base.js
  services/blockchain-service/implementations/browser-blockchain-service.js
  services/blockchain-service/implementations/node-blockchain-service.js
  webpack.config.js
Labels: bug

#100 Updated README, added LICENSE and CONTRIBUTIONS files
  .DS_Store
  CONTRIBUTIONS
  LICENSE
  README.md
  header.png
  images/banner.jpg
  images/dkg-architecture.png
  images/icons/coinmarketcap.svg
  images/icons/discord.svg
  images/icons/linkedin.svg
  images/icons/medium.svg
  images/icons/reddit.svg
  images/icons/telegram.svg
  images/icons/x.svg
  images/icons/youtube.svg
  images/ka.png
  images/knowledge-assets-graph1.svg
  images/knowledge-assets-graph2.svg
  images/knowledge-assets-graph3.svg
  images/knowledge-assets-graph4.svg
  images/nodes.png
Labels: documentation
