Repository OriginTrail/dkg.js, pull requests merged in 2023-03, with the labels that each got.

#66 allow for custom blockchains
  services/blockchain-service/blockchain-service-base.js
  services/blockchain-service/implementations/node-blockchain-service.js
Labels: bug

#65 Handle get private assertion
  constants.js
  examples/demo.js
  managers/asset-operations-manager.js
  managers/graph-operations-manager.js
  services/blockchain-service/blockchain-service-base.js
  services/blockchain-service/implementations/node-blockchain-service.js
  services/input-service.js
  services/node-api-service/implementations/http-service.js
  services/utilities.js
  services/validation-service.js
Labels: bug

#68 Bid suggestion + bugs fixes
  managers/asset-operations-manager.js
  services/blockchain-service/blockchain-service-base.js
Labels: bug, enhancement

#63 Update feature
  .eslintrc.js
  constants.js
  examples/demo.js
  managers/asset-operations-manager.js
  managers/graph-operations-manager.js
  managers/node-operations-manager.js
  package-lock.json
  package.json
  services/blockchain-service/blockchain-service-base.js
  services/blockchain-service/implementations/node-blockchain-service.js
  services/input-service.js
  services/node-api-service/implementations/http-service.js
  services/utilities.js
  services/validation-service.js
Labels: enhancement
